export const topics: { id: number; name: string }[] = [
  { id: 1, name: "Psicología" },
  { id: 2, name: "Salud" },
  { id: 3, name: "Productividad" },
  { id: 4, name: "Educación" },
  { id: 5, name: "Filosofía" },
  { id: 6, name: "Ciencia" },
  { id: 7, name: "Tecnología" },
  { id: 8, name: "Inteligencia Artificial" },
  { id: 9, name: "Programación" },
  { id: 10, name: "Desarrollo" },
  { id: 11, name: "Diseño" },
  { id: 12, name: "Arte" },
  { id: 13, name: "Idiomas" },
  { id: 14, name: "Negocios" },
  { id: 15, name: "Marketing" },
  { id: 16, name: "Finanzas" },
  { id: 17, name: "Gaming" },
  { id: 18, name: "Religión" },
];
